// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PermitPro.Core.Data;

#nullable disable

namespace PermitPro.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240713101435_AddNewProperty-PreviousPermitStatus-Permit")]
    partial class AddNewPropertyPreviousPermitStatusPermit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CertificatePermit", b =>
                {
                    b.Property<Guid>("CertificatesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermitsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CertificatesId", "PermitsId");

                    b.HasIndex("PermitsId");

                    b.ToTable("PermitsCertificates", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PermitPro.Core.Data.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PermitPro.Core.Data.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressCompanyId");

                    b.HasIndex("AddressContactId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("PermitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("PermitId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuditLogUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("SerializedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Home")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonInCharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentDivisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentHeadId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentSupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentDivisionId");

                    b.HasIndex("DepartmentHeadId");

                    b.HasIndex("DepartmentSupervisorId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisionHeadId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("DivisionSiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DivisionSupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DivisionHeadId");

                    b.HasIndex("DivisionSiteId");

                    b.HasIndex("DivisionSupervisorId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Permit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoResumeSuspended")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermitForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitHolderCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermitHolderNumOfStaff")
                        .HasColumnType("int");

                    b.Property<string>("PermitNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermitStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("PermitWorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PermitWorkflowStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PreviousPermitStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunningNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SuspendedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PermitWorkflowId");

                    b.HasIndex("PermitWorkflowStepId");

                    b.HasIndex("SiteId");

                    b.ToTable("Permits");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.PermitNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermitNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermitNumbers");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ShowInMap")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SiteCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteType")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SiteCompanyId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.SystemMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemMenus");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserCompanyId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCertificate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WorkflowCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowCompanyId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.WorkflowHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HistoryWorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HistoryWorkflowStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PermitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RejectedWhen")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HistoryWorkflowId");

                    b.HasIndex("HistoryWorkflowStepId");

                    b.HasIndex("PermitId");

                    b.ToTable("WorkflowHistories");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowMove")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("DurationType")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirst")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLast")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedWhen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WorkflowStepWorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStepWorkflowId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("RoleSystemMenu", b =>
                {
                    b.Property<string>("RolesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SystemMenusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "SystemMenusId");

                    b.HasIndex("SystemMenusId");

                    b.ToTable("SystemMenusRoles", (string)null);
                });

            modelBuilder.Entity("SiteUserInfo", b =>
                {
                    b.Property<Guid>("SitesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SitesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("SiteUserInfo");
                });

            modelBuilder.Entity("UserInfoWorkflowStep", b =>
                {
                    b.Property<string>("ApproversId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("WorkflowStepsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApproversId", "WorkflowStepsId");

                    b.HasIndex("WorkflowStepsId");

                    b.ToTable("ApproversWorkflowSteps", (string)null);
                });

            modelBuilder.Entity("CertificatePermit", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Certificate", null)
                        .WithMany()
                        .HasForeignKey("CertificatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PermitPro.Core.Entities.Permit", null)
                        .WithMany()
                        .HasForeignKey("PermitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("PermitPro.Core.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermitPro.Core.Data.UserRole", b =>
                {
                    b.HasOne("PermitPro.Core.Data.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PermitPro.Core.Entities.UserInfo", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Address", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Company", "AddressCompany")
                        .WithMany("CompanyAddresses")
                        .HasForeignKey("AddressCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PermitPro.Core.Entities.Contact", "AddressContact")
                        .WithMany()
                        .HasForeignKey("AddressContactId");

                    b.Navigation("AddressCompany");

                    b.Navigation("AddressContact");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Attachment", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId");

                    b.HasOne("PermitPro.Core.Entities.Permit", "Permit")
                        .WithMany("Attachments")
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Certificate");

                    b.Navigation("Permit");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.UserInfo", "AuditLogUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AuditLogUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AuditLogUser");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Department", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Division", "DepartmentDivision")
                        .WithMany("DivisionDepartments")
                        .HasForeignKey("DepartmentDivisionId");

                    b.HasOne("PermitPro.Core.Entities.UserInfo", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadId");

                    b.HasOne("PermitPro.Core.Entities.UserInfo", "DepartmentSupervisor")
                        .WithMany()
                        .HasForeignKey("DepartmentSupervisorId");

                    b.Navigation("DepartmentDivision");

                    b.Navigation("DepartmentHead");

                    b.Navigation("DepartmentSupervisor");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Division", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.UserInfo", "DivisionHead")
                        .WithMany()
                        .HasForeignKey("DivisionHeadId");

                    b.HasOne("PermitPro.Core.Entities.Site", "DivisionSite")
                        .WithMany()
                        .HasForeignKey("DivisionSiteId");

                    b.HasOne("PermitPro.Core.Entities.UserInfo", "DivisionSupervisor")
                        .WithMany()
                        .HasForeignKey("DivisionSupervisorId");

                    b.Navigation("DivisionHead");

                    b.Navigation("DivisionSite");

                    b.Navigation("DivisionSupervisor");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Notification", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.UserInfo", "NotificationUser")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NotificationUser");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Permit", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Company", "Company")
                        .WithMany("CompanyPermits")
                        .HasForeignKey("CompanyId");

                    b.HasOne("PermitPro.Core.Entities.Workflow", "PermitWorkflow")
                        .WithMany("WorkflowPermits")
                        .HasForeignKey("PermitWorkflowId");

                    b.HasOne("PermitPro.Core.Entities.WorkflowStep", "PermitWorkflowStep")
                        .WithMany()
                        .HasForeignKey("PermitWorkflowStepId");

                    b.HasOne("PermitPro.Core.Entities.Site", "Site")
                        .WithMany("Permits")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("PermitWorkflow");

                    b.Navigation("PermitWorkflowStep");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Site", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Company", "SiteCompany")
                        .WithMany("CompanySites")
                        .HasForeignKey("SiteCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SiteCompany");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.UserInfo", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Company", "UserCompany")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserCompanyId");

                    b.Navigation("UserCompany");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Workflow", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Company", "WorkflowCompany")
                        .WithMany("CompanyWorkflows")
                        .HasForeignKey("WorkflowCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("WorkflowCompany");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.WorkflowHistory", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Workflow", "HistoryWorkflow")
                        .WithMany("WorkflowHistories")
                        .HasForeignKey("HistoryWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PermitPro.Core.Entities.WorkflowStep", "HistoryWorkflowStep")
                        .WithMany()
                        .HasForeignKey("HistoryWorkflowStepId");

                    b.HasOne("PermitPro.Core.Entities.Permit", "Permit")
                        .WithMany("WorkflowHistories")
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HistoryWorkflow");

                    b.Navigation("HistoryWorkflowStep");

                    b.Navigation("Permit");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.WorkflowStep", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Workflow", "WorkflowStepWorkflow")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowStepWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("WorkflowStepWorkflow");
                });

            modelBuilder.Entity("RoleSystemMenu", b =>
                {
                    b.HasOne("PermitPro.Core.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PermitPro.Core.Entities.SystemMenu", null)
                        .WithMany()
                        .HasForeignKey("SystemMenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteUserInfo", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.Site", null)
                        .WithMany()
                        .HasForeignKey("SitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PermitPro.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserInfoWorkflowStep", b =>
                {
                    b.HasOne("PermitPro.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("ApproversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PermitPro.Core.Entities.WorkflowStep", null)
                        .WithMany()
                        .HasForeignKey("WorkflowStepsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermitPro.Core.Data.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Company", b =>
                {
                    b.Navigation("CompanyAddresses");

                    b.Navigation("CompanyPermits");

                    b.Navigation("CompanySites");

                    b.Navigation("CompanyUsers");

                    b.Navigation("CompanyWorkflows");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Division", b =>
                {
                    b.Navigation("DivisionDepartments");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Permit", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("WorkflowHistories");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Site", b =>
                {
                    b.Navigation("Permits");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.UserInfo", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PermitPro.Core.Entities.Workflow", b =>
                {
                    b.Navigation("WorkflowHistories");

                    b.Navigation("WorkflowPermits");

                    b.Navigation("WorkflowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
