name: Build project and deploy to SmarterASP.NET
on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed (merged)
    branches:
      - master # Target branch for pull request merges

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    name: Build and Deploy
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '10.0.x'

        - name: Install dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release --no-restore

        - name: Publish
          run: dotnet publish Web/App.csproj --configuration Release --framework net10.0 --output ./publish --runtime win-x64 --self-contained -p:PublishReadyToRun=true

        - name: SmarterASP.NET Web Deploy
          uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
          with:
            website-name: ${{ secrets.WEBSITE_NAME_UAT }}
            server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME_UAT }}
            server-username: ${{ secrets.SERVER_USERNAME_UAT }}
            server-password: ${{ secrets.SERVER_PASSWORD_UAT }}
            target-delete: true
